### ISSUE TITLE
Cambios a realizar

### ISSUE THREAD

**Issue by RobertoReyRodriguez** [polioubinha/Piscifactoria#1]
### Cambios a revisar antes de empezar piscifactoría:

- [x] #2
- [x] Mostrar los dos tipos de piscifactoría
- [x] Revisar Alimentar.
- [x] Revisar e implementar menú helper.
- [x] Cambiar almacén para que esté vacío cuando compra.
- [x] Revisar comer
- [x] Revisar excepción al pasar días
- [x] Echar un ojo al método nextDayReproduccion, posible error de concurrencia
- [x] Mover ganancias y atributos temporales.
- [x] Añadir descuento a la comida cuando es del almacén(revisar)
- [x] AddFood en el mismo if.
- [x] #3

### Documentacion:

- Nombre de método como título y debajo la cabecera
- Definir parametros
- Explicar que representa cada clase, añadir javadoc a métodos que faltan.

**Comment by polioubinha** [comment]
1. **Echar un ojo al método nextDayReproduccion, posible error de concurrencia**

-> Se marca el método con "synchronized" para evitar que varios hilos puedan acceder a este a la vez.
